# Invoke-Automation Windows Dockerfile

# Indicates that the windowsservercore image will be used as the base image.
FROM microsoft/windowsservercore

# Metadata indicating an image maintainer.
MAINTAINER jpsider

# Copy PowerNSX Module to container
ADD https://raw.github.com/vmware/powernsx/master/PowerNSX.psm1 c:/temp/

# Add powershell scripts
COPY . c:/temp/

# Validate Imported Modules
RUN powershell -executionpolicy bypass c:\temp\InstallModules.ps1;c:\temp\ImportModules.ps1

# Start powershell
CMD [ "powershell" ] 